### ISSUE TITLE
Manuel input for network

### ISSUE THREAD

**Issue by rothestar** [openenergymonitor/EmonESP#25] opened 2017-05-26 11:23 UTC
It would be nice if the emonESP would have an input field where I could do input of the following:
1: SSID (hidden not transmitting)
2: No dhcp (manual input of IP-address)
3: subnet
4: gateway

**Comment by glynhudson** [comment] 2018-01-24 14:08
Thanks, I agree. This is a duplicate of issue  #23

**Closed by glynhudson** 2018-01-24 14:08 UTC
